const translations = {
    en: {
        searchPlaceholder: "Search by name...",
        allTypesOption: "All Types",
        cityOption: "City",
        beachOption: "Beach",
        natureOption: "Nature",
        historyOption: "History",
        itineraryTitle: "My Trip Itinerary",
        removeFromItinerary: "Remove",
        addToItinerary: "Add to Itinerary",
        inItinerary: "In Itinerary",
        addedToItinerary: "Added!",
        moreInfoLink: "More Info",
        bookingsLink: "Bookings",
        languageSwitcherLabel: "Language:",
        averageRatingPopup: "Avg. Rating",
        reviewCountSingular: "review",
        reviewCountPlural: "reviews",
        noReviewsYetPopup: "No reviews yet",
        viewAddReviewBtn: "View / Add Review",
        reviewsFor: "Reviews for",
        averageRatingModal: "Average Rating",
        noReviewsYet: "No reviews yet.",
        addReviewTitle: "Add Your Review",
        userNameLabel: "Name (Optional):",
        ratingLabel: "Your Rating:",
        reviewTextLabel: "Your Review:",
        submitReviewBtn: "Submit Review",
        anonymousUser: "Anonymous",
        selectRatingAlert: "Please select a star rating.",
        writeReviewAlert: "Please write a review.",
        dreamModeButton: "Dream Mode",
        dreamModeActive: "Dream Mode Active: Map interaction disabled",
        exploreButton: "Explore",
        triviaButton: "Trivia",
        triviaModalTitle: "Did you know?",
        generativeModeButton: "Generative",
        starRatingAriaLabel: "{score} out of 5 stars",
        missionPlanTitle: "Mission Plan",
        missionControlToggle: "Mission Control",
        targetsStats: "Targets",
        abortMissionBtn: "Abort Mission",
        closeMissionControlAria: "Close Mission Control",
        searchAria: "Search attractions",
        filterAria: "Filter attractions by type",
        noTargets: "No targets selected.",
        moveUpAria: "Move {name} up",
        moveDownAria: "Move {name} down",
        missionAborted: "Mission aborted: No targets selected.",
        totalDistance: "Total Distance",
        executeRecon: "Execute Recon",
        opsCenterTitle: "S.C.O.U.T. OPS CENTER",
        systemInitialized: "System initialized... awaiting data.",
        droneUplink: "DRONE UPLINK",
        liveIntelFeed: "LIVE INTEL FEED",
        activeDrones: "Active Drones",
        signalStrength: "Signal Strength",
        deployInstruction: "Select a target on map to deploy.",
        opsCenterBtn: "OPS CENTER",
        droneMaxCapacity: "Maximum drone capacity reached. Recall a drone first.",
        launchingDrone: "Launching drone to {target}...",
        droneArrived: "Drone arrived at {target}. Scanning...",
        scanComplete: "SCAN COMPLETE: {target} | Density: {density}% | Wait: {wait}m",
        intelUnlockedAlert: "CLASSIFIED INTEL UNLOCKED FOR {target}:\n\nCurrent Crowd Density: {density}%\nEstimated Wait Time: {wait} mins\n\nSecret: Locals recommend visiting the nearby back-alley cafe for the best view."
    },
    sq: { // Albanian
        searchPlaceholder: "Kërko sipas emrit...",
        allTypesOption: "Të gjitha Llojet",
        cityOption: "Qytet",
        beachOption: "Plazh",
        natureOption: "Natyror",
        historyOption: "Historik",
        itineraryTitle: "Itinerari im",
        removeFromItinerary: "Hiqe",
        addToItinerary: "Shto në Itinerar",
        inItinerary: "Në Itinerar",
        addedToItinerary: "Shtuar!",
        moreInfoLink: "Më shumë Info",
        bookingsLink: "Rezervime",
        languageSwitcherLabel: "Gjuha:",
        averageRatingPopup: "Vler. Mes.",
        reviewCountSingular: "vlerësim",
        reviewCountPlural: "vlerësime",
        noReviewsYetPopup: "Ende pa vlerësime",
        viewAddReviewBtn: "Shiko / Shto Vlerësim",
        reviewsFor: "Vlerësimet për",
        averageRatingModal: "Vlerësimi Mesatar",
        noReviewsYet: "Ende asnjë vlerësim.",
        addReviewTitle: "Shto Vlerësimin Tënd",
        userNameLabel: "Emri (Opsional):",
        ratingLabel: "Vlerësimi juaj:",
        reviewTextLabel: "Shkruaj vlerësimin:",
        submitReviewBtn: "Dërgo Vlerësimin",
        anonymousUser: "Anonim",
        selectRatingAlert: "Ju lutemi zgjidhni një vlerësim me yje.",
        writeReviewAlert: "Ju lutemi shkruani një vlerësim.",
        dreamModeButton: "Modaliteti i Ëndrrave",
        dreamModeActive: "Modaliteti i Ëndrrave Aktiv: Ndërveprimi me hartën është çaktivizuar",
        exploreButton: "Eksploro",
        triviaButton: "Trivia",
        triviaModalTitle: "A e dini?",
        generativeModeButton: "Gjenerues",
        starRatingAriaLabel: "{score} nga 5 yje",
        missionPlanTitle: "Plani i Misionit",
        missionControlToggle: "Kontrolli i Misionit",
        targetsStats: "Objektivat",
        abortMissionBtn: "Anulo Misionin",
        closeMissionControlAria: "Mbyll Kontrollin e Misionit",
        searchAria: "Kërko atraksionet",
        filterAria: "Filtro atraksionet sipas llojit",
        noTargets: "Asnjë objektiv i zgjedhur.",
        moveUpAria: "Lëviz {name} lart",
        moveDownAria: "Lëviz {name} poshtë",
        missionAborted: "Misioni u anulua: Asnjë objektiv i zgjedhur.",
        totalDistance: "Distanca Totale",
        executeRecon: "Ekzekuto Zbulimin",
        opsCenterTitle: "QENDRA OPERACIONALE S.C.O.U.T.",
        systemInitialized: "Sistemi u inicializua... në pritje të të dhënave.",
        droneUplink: "LIDHJA E DRONIT",
        liveIntelFeed: "FURNIZIMI I DREJTPËRDREJTË I INTELIGJENCËS",
        activeDrones: "Dronë Aktivë",
        signalStrength: "Fuqia e Sinjalit",
        deployInstruction: "Zgjidhni një objektiv në hartë për të vendosur.",
        opsCenterBtn: "QENDRA OPS",
        droneMaxCapacity: "Kapaciteti maksimal i dronëve u arrit. Ktheni një dron fillimisht.",
        launchingDrone: "Duke lëshuar dronin në {target}...",
        droneArrived: "Droni mbërriti në {target}. Duke skanuar...",
        scanComplete: "SKANIM I PLOTË: {target} | Dendësia: {density}% | Pritja: {wait}m",
        intelUnlockedAlert: "INTELIGJENCA E KLASIFIKUAR U HAP PËR {target}:\n\nDendësia Aktuale e Turmës: {density}%\nKoha e Vlerësuar e Pritjes: {wait} minuta\n\nSekret: Vendasit rekomandojnë vizitën në kafenenë e fshehur aty pranë për pamjen më të mirë."
    }
};
