const translations = {
    en: {
        searchPlaceholder: "Search by name...",
        allTypesOption: "All Types",
        cityOption: "City",
        beachOption: "Beach",
        natureOption: "Nature",
        historyOption: "History",
        itineraryTitle: "My Trip Itinerary",
        removeFromItinerary: "Remove",
        addToItinerary: "Add to Itinerary",
        inItinerary: "In Itinerary",
        addedToItinerary: "Added!",
        moreInfoLink: "More Info",
        bookingsLink: "Bookings",
        languageSwitcherLabel: "Language:",
        averageRatingPopup: "Avg. Rating",
        reviewCountSingular: "review",
        reviewCountPlural: "reviews",
        noReviewsYetPopup: "No reviews yet",
        viewAddReviewBtn: "View / Add Review",
        reviewsFor: "Reviews for",
        averageRatingModal: "Average Rating",
        noReviewsYet: "No reviews yet.",
        addReviewTitle: "Add Your Review",
        userNameLabel: "Name (Optional):",
        ratingLabel: "Your Rating:",
        reviewTextLabel: "Your Review:",
        submitReviewBtn: "Submit Review",
        anonymousUser: "Anonymous",
        selectRatingAlert: "Please select a star rating.",
        writeReviewAlert: "Please write a review.",
        dreamModeButton: "Dream Mode",
        exploreButton: "Explore"
    },
    sq: { // Albanian
        searchPlaceholder: "Kërko sipas emrit...",
        allTypesOption: "Të gjitha Llojet",
        cityOption: "Qytet",
        beachOption: "Plazh",
        natureOption: "Natyror",
        historyOption: "Historik",
        itineraryTitle: "Itinerari im",
        removeFromItinerary: "Hiqe",
        addToItinerary: "Shto në Itinerar",
        inItinerary: "Në Itinerar",
        addedToItinerary: "Shtuar!",
        moreInfoLink: "Më shumë Info",
        bookingsLink: "Rezervime",
        languageSwitcherLabel: "Gjuha:",
        averageRatingPopup: "Vler. Mes.",
        reviewCountSingular: "vlerësim",
        reviewCountPlural: "vlerësime",
        noReviewsYetPopup: "Ende pa vlerësime",
        viewAddReviewBtn: "Shiko / Shto Vlerësim",
        reviewsFor: "Vlerësimet për",
        averageRatingModal: "Vlerësimi Mesatar",
        noReviewsYet: "Ende asnjë vlerësim.",
        addReviewTitle: "Shto Vlerësimin Tënd",
        userNameLabel: "Emri (Opsional):",
        ratingLabel: "Vlerësimi juaj:",
        reviewTextLabel: "Shkruaj vlerësimin:",
        submitReviewBtn: "Dërgo Vlerësimin",
        anonymousUser: "Anonim",
        selectRatingAlert: "Ju lutemi zgjidhni një vlerësim me yje.",
        writeReviewAlert: "Ju lutemi shkruani një vlerësim.",
        dreamModeButton: "Modaliteti i Ëndrrave",
        exploreButton: "Eksploro"
    }
};
